---
- name: Ensure OS version is EL7
  assert:
    that:
      - "ansible_os_family == 'RedHat'"
      - "ansible_facts['distribution_major_version'] == '7'"
    success_msg: "{{ ansible_os_family  }} {{ ansible_facts['distribution_major_version'] }} is supported."
    fail_msg: "{{ ansible_os_family }} {{ ansible_facts['distribution_major_version'] }} is not supported."
  tags:
    - keepalived

- name: Install yum Copr repo for keepalived owned by ashleykleynhans
  yum_repository:
    name: "{{ keepalived_repo_name }}"
    description: "{{ keepalived_repo_desc }}"
    baseurl: "{{ keepalived_repo_url }}/epel-{{ ansible_facts['distribution_major_version'] }}-$basearch/"
    gpgcheck: True
    gpgkey: "{{ keepalived_yum_gpg_key }}"
    proxy: _none_
    includepkgs: "{{ epel_includepkgs | default(omit) }}"
  tags:
    - keepalived

- name: Install keepalived
  package:
    name: "{{ keepalived_package_name }}"
    state: "{{ keepalived_package_state }}"
  tags:
    - keepalived

- name: Include role evrardjp.keepalived
  include_role:
    name: evrardjp.keepalived
    apply:
      tags:
        - keepalived
  tags:
    - keepalived

- name: Ensure no new "keepalived.conf.rpmnew" file appeared
  file:
    path: /etc/keepalived/keepalived.conf.rpmnew
    state: absent
  tags:
    - keepalived

- name: Install keepalived common logging function for bash scripts
  copy:
    src: files/bash_logging.sh
    dest: /etc/keepalived/bash_logging.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - keepalived

- name: Install keepalived notification script for MASTER status
  copy:
    src: files/notify_master.sh
    dest: /etc/keepalived/notify_master.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - keepalived

- name: Install keepalived notification script for BACKUP status
  copy:
    src: files/notify_backup.sh
    dest: /etc/keepalived/notify_backup.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - keepalived

- name: Install keepalived notification script for STOPPED status
  copy:
    src: files/notify_stop.sh
    dest: /etc/keepalived/notify_stop.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - keepalived

- name: Install keepalived notification script for FAULT status
  copy:
    src: files/notify_fault.sh
    dest: /etc/keepalived/notify_fault.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - keepalived

- name: Insert additional commands to the MASTER notification script
  lineinfile:
    path: /etc/keepalived/notify_master.sh
    line: "{{ item }}"
  with_items: "{{ keepalived_additional_notify_master }}"
  when: keepalived_additional_notify_master is defined
  tags:
    - keepalived

- name: Insert additional commands to the BACKUP notification script
  lineinfile:
    path: /etc/keepalived/notify_backup.sh
    line: "{{ item }}"
  with_items: "{{ keepalived_additional_notify_backup }}"
  when: keepalived_additional_notify_backup is defined
  tags:
    - keepalived

- name: Insert additional commands to the STOPPED notification script
  lineinfile:
    path: /etc/keepalived/notify_stop.sh
    line: "{{ item }}"
  with_items: "{{ keepalived_additional_notify_stop }}"
  when: keepalived_additional_notify_stop is defined
  tags:
    - keepalived

- name: Insert additional commands to the FAULT notification script
  lineinfile:
    path: /etc/keepalived/notify_fault.sh
    line: "{{ item }}"
  with_items: "{{ keepalived_additional_notify_fault }}"
  when: keepalived_additional_notify_fault is defined
  tags:
    - keepalived
